// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJgKje6ezFLPWSDQgHpnJC8tV3Pu79ygw',
    appId: '1:345279725758:web:aa26b666049ef3b656deef',
    messagingSenderId: '345279725758',
    projectId: 'project-5321183510433372495',
    authDomain: 'project-5321183510433372495.firebaseapp.com',
    storageBucket: 'project-5321183510433372495.appspot.com',
    measurementId: 'G-RWJ0493N00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAu-B5h-Eayq-PcKSA1nKXz94Spfwil8U',
    appId: '1:345279725758:android:158defac9dda9f1656deef',
    messagingSenderId: '345279725758',
    projectId: 'project-5321183510433372495',
    storageBucket: 'project-5321183510433372495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeT1u8zCNenAaGKRrDK2PHxmBRiTrfbMk',
    appId: '1:345279725758:ios:165ab7fa372cf25a56deef',
    messagingSenderId: '345279725758',
    projectId: 'project-5321183510433372495',
    storageBucket: 'project-5321183510433372495.appspot.com',
    iosBundleId: 'com.example.justLike',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeT1u8zCNenAaGKRrDK2PHxmBRiTrfbMk',
    appId: '1:345279725758:ios:bc561e97a76fbec656deef',
    messagingSenderId: '345279725758',
    projectId: 'project-5321183510433372495',
    storageBucket: 'project-5321183510433372495.appspot.com',
    iosBundleId: 'com.example.justLike.RunnerTests',
  );
}
